# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iOS_assignment3' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iOS_assignment3

  target 'iOS_assignment3Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iOS_assignment3UITests' do
    # Pods for testing
  end

  pod 'Alamofire'
end
